name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Run Security Scan & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install dependencies
        run: npm install
      
      - name: Run Unit Tests
        run: npm test

  build-and-push:
    name: Build & Push Docker Image
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login mycontainerregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t mycontainerregistry.azurecr.io/myapp:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push mycontainerregistry.azurecr.io/myapp:${{ github.sha }}

  deploy-to-aks:
    name: Deploy to AKS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-kubectl@v3

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group aks-resource-group --name my-aks-cluster

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

  selenium-tests:
    name: Run Selenium UI Tests
    needs: deploy-to-aks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Selenium
        run: pip install selenium

      - name: Run Selenium Tests
        run: python tests/selenium_test.py

